"""Initial migration

Revision ID: c477e1f02bdb
Revises: 
Create Date: 2025-06-04 03:30:42.071982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c477e1f02bdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_depth')
    op.drop_column('tasks', 'format')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'username')
    op.add_column('tasks', sa.Column('format', sa.VARCHAR(), nullable=True))
    op.add_column('tasks', sa.Column('max_depth', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
